version: '3'
services:
  
  notebook:
    image: jupyter/pyspark-notebook
    ports:
      - 8888:8888
      - 4040:4040
    environment:
      - PYSPARK_SUBMIT_ARGS=--packages com.amazonaws:aws-java-sdk-bundle:1.11.563,org.apache.hadoop:hadoop-aws:3.2.2 pyspark-shell
    volumes:
      - ./jupyter-data:/data

  minio:
    hostname: minio
    image: 'minio/minio:RELEASE.2021-12-29T06-49-06Z'
    container_name: minio
    ports:
      - '9595:9000'   # API
      - '38000:38000' # console
    volumes:
      - ./minio-data:/data
    environment:
      MINIO_ROOT_USER: minio_access_key
      MINIO_ROOT_PASSWORD: minio_secret_key
    command: server /data --console-address ":38000"
  
  mariadb:
    hostname: mariadb
    image: mariadb:10.7.1
    container_name: mariadb
    ports:
      - 3306:3306
    volumes:
      - ./mariadb-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: metastore_db

  hive-metastore:
    hostname: hive-metastore
    container_name: hive-metastore
    image: 'bitsondatadev/hive-metastore:latest'
    ports:
      - '9083:9083' # Metastore Thrift
    volumes:
      - ./hive/conf/metastore-site.xml:/opt/apache-hive-metastore-3.0.0-bin/conf/metastore-site.xml:ro
    environment:
      METASTORE_DB_HOSTNAME: mariadb
    depends_on:
      - mariadb

  trino-coordinator:
    image: "trinodb/trino:367"
    container_name: trino
    ports:
      - '8080:8080'
    volumes:
      - ./trino/coordinator/etc:/etc/trino:ro
    depends_on:
      - hive-metastore

  superset:
    build: ./superset
    ports:
      - "8088:8088"
    volumes:
      - ./superset-data:/app/superset_home

 